[package]
name = "bplist"
version = "0.1.0"
authors = ["Martin Mroz <martinmroz@gmail.com>"]
edition = "2018"

[dependencies]
ascii = "1"
nom = "5"
ordered-float = "2"
serde = { version = "1.0", features = ["derive"] }
